name: Setup

runs:
  using: "composite"
  steps:
    - name: Setup Nix
      uses: ./.github/actions/setup-nix

    - name: Install dependencies
      uses: ./.github/actions/install

    - name: Setup Turborepo Cache Server
      uses: ./.github/actions/setup-turbo
