[build]
  base = "docs"
  publish = "docs/.next"
  command = "pnpm install && pnpm --filter @snaplet/documentation build"
[build.environment]
  NODE_VERSION = "20.12.2" 
[[plugins]]
  package = "@netlify/plugin-nextjs"