name: Build and Publish alpha release

on:
  push:
    branches:
      - main
      - chore/setup-alpha-releases

concurrency:
  group: publish-alpha-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
    
      - name: Set short-sha
        id: short-sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Publish alpha package
        working-directory: ./packages/seed
        run: npx tsx ./scripts/release-alpha.mts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_HASH: ${{ steps.short-sha.outputs.sha_short }}
