name: Release Latest

on:
  release:
    types: [published]

concurrency:
  group: release-npm
  cancel-in-progress: false

defaults:
  run:
    shell: devenv {0}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build-and-publish:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish package
        uses: ./.github/actions/publish
        with:
          channel: latest
          token: ${{ secrets.NPM_TOKEN }}

      - name: Publish release note to docs.snaplet.dev
        run: pnpm -F @snaplet/seed run publish:docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_COMMIT }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Publish release note to Discord
        run: pnpm -F @snaplet/seed run publish:discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT_COMMIT }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}