name: Release Alpha

on:
  push:
    branches:
      - main
      - chore/setup-alpha-releases

concurrency:
  group: release-alpha-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: devenv {0}

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-and-publish:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
    
      - name: Set short-sha
        id: short-sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Clean build
        run: pnpm clean

      - name: Publish alpha package
        working-directory: ./packages/seed
        run: pnpm run release:alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_HASH: ${{ steps.short-sha.outputs.sha_short }}
