name: Release Latest

on:
  release:
    types: [published]

concurrency:
  group: release-npm
  cancel-in-progress: false

defaults:
  run:
    shell: devenv {0}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build-and-publish:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish
        uses: ./.github/actions/publish
        with:
          channel: latest
          token: ${{ secrets.NPM_TOKEN }}
