name: Release Latest

on:
  release:
    types: [published]

concurrency:
  group: release-npm
  cancel-in-progress: false

defaults:
  run:
    shell: devenv {0}

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

jobs:
  build-and-publish:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup npmrc auth for publish
        run: |
          echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' >> .npmrc && \
          echo "registry=https://registry.npmjs.org/" >> .npmrc && \
          echo "always-auth=true" >> .npmrc

      - name: Publish latest package
        run: pnpm -F @snaplet/seed run release:latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
