name: Tag release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/seed/package.json'

concurrency:
  group: tag-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-release:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2
        with:
          path: packages/seed

      - name: Push a new tag on git repo
        if: steps.cpv.outputs.is-new-version == 'true'
        uses: Klemensas/action-autotag@stable
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          package_root: "packages/seed"
          tag_prefix: "v"